markdown: rdiscount
permalink: /:title/
url: http://look1988.github.io
name: Look
author: Look
qq: 630201142
email: 630201142@qq.com
duoshuo: yonsm
beian: 
cnzz: 
weibo: 13716140933
github: look1988
pygments: true
safe: true
paginate: 20
about: "切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
